// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6Y23kmMgblPJXogoHFltXzh2BlEpk7Y',
    appId: '1:917279003258:web:10d18bfbc03ec9773121c3',
    messagingSenderId: '917279003258',
    projectId: 'aurify-fd4d3',
    authDomain: 'aurify-fd4d3.firebaseapp.com',
    storageBucket: 'aurify-fd4d3.firebasestorage.app',
    measurementId: 'G-663W8S9DVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sCo9WOuMrO5NdzPqIGnVFW_3rORX4ZE',
    appId: '1:917279003258:android:c57efdf9065bd1573121c3',
    messagingSenderId: '917279003258',
    projectId: 'aurify-fd4d3',
    storageBucket: 'aurify-fd4d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaVIxdbMnsV-IgdFZkDk34SpBIAg45jFE',
    appId: '1:917279003258:ios:3fcc247b16667e483121c3',
    messagingSenderId: '917279003258',
    projectId: 'aurify-fd4d3',
    storageBucket: 'aurify-fd4d3.firebasestorage.app',
    iosBundleId: 'com.example.aurify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaVIxdbMnsV-IgdFZkDk34SpBIAg45jFE',
    appId: '1:917279003258:ios:3fcc247b16667e483121c3',
    messagingSenderId: '917279003258',
    projectId: 'aurify-fd4d3',
    storageBucket: 'aurify-fd4d3.firebasestorage.app',
    iosBundleId: 'com.example.aurify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ6Y23kmMgblPJXogoHFltXzh2BlEpk7Y',
    appId: '1:917279003258:web:26ee41d6ae3ca5ce3121c3',
    messagingSenderId: '917279003258',
    projectId: 'aurify-fd4d3',
    authDomain: 'aurify-fd4d3.firebaseapp.com',
    storageBucket: 'aurify-fd4d3.firebasestorage.app',
    measurementId: 'G-FH49QJXHZW',
  );
}
